version: "3.8"

services:
    frontend:
        working_dir: /frontend
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env.production
        environment:
            - NUXT_HOST=0.0.0.0
            - NUXT_PORT=80
            - NITRO_HOST=0.0.0.0
            - NITRO_PORT=80
        ports:
            - "3000:80"
