version: "3.8"

services:
  proxy:
    ports:
      - "80:80"
      - "443:443"
    command:
      - --accesslog
      - --certificatesresolvers.default.acme.email=tech@game-values.com
      - --certificatesresolvers.default.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.default.acme.storage=/app/acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=default
      - --log
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`, `${TRAEFIK_TAG?Variable not set}`)
      - --providers.docker.exposedbydefault=false

  frontend:
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
      - traefik.http.middlewares.${STACK_NAME?Variable not set}-https-redirect.redirectscheme.permanent=true
      - traefik.http.middlewares.${STACK_NAME?Variable not set}-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.${STACK_NAME?Variable not set}-www-http.middlewares=${STACK_NAME?Variable not set}-https-redirect
      - traefik.http.routers.${STACK_NAME?Variable not set}-www-http.rule=PathPrefix(`/`) && (Host(`www.${VUE_APP_DOMAIN_PROD?Variable not set}`) || Host(`${VUE_APP_DOMAIN_PROD?Variable not set}`))
      - traefik.http.routers.${STACK_NAME?Variable not set}-www-https.entrypoints=websecure
      - traefik.http.routers.${STACK_NAME?Variable not set}-www-https.rule=Host(`www.${VUE_APP_DOMAIN_PROD?Variable not set}`) || Host(`${VUE_APP_DOMAIN_PROD?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-www-https.tls.certresolver=default
      - traefik.http.routers.${STACK_NAME?Variable not set}-www-https.tls=true
      - traefik.http.services.${STACK_NAME?Variable not set}-www.loadbalancer.server.port=80
