<template>
<v-row>
    <v-column>
        <ui-image
            src="https://raw.githubusercontent.com/Game-Values/web-ui-widgets/master/src/public/images/development-settings-referral.png"
        />
    </v-column>
</v-row>
</template>
