export { default as FooterCopyright } from "~/widgets/footer/ui/footer-copyright.svelte"
export { default as FooterLink } from "~/widgets/footer/ui/footer-link.svelte"
export { default as FooterLinks } from "~/widgets/footer/ui/footer-links.svelte"
export { default as FooterLogo } from "~/widgets/footer/ui/footer-logo.svelte"
export { default as FooterPayments } from "~/widgets/footer/ui/footer-payments.svelte"
export { default as FooterSocialsLinks } from "~/widgets/footer/ui/footer-socials-links.svelte"
export { default as Footer } from "~/widgets/footer/ui/footer.svelte"
