/* eslint-disable */
/**
 * This file was generated by 'vite-plugin-kit-routes'
 *
 *      >> DO NOT EDIT THIS FILE MANUALLY <<
 */

/**
 * PAGES
 */
const PAGES = {
  "/": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: '/'}`
  },
  "/favorites": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/favorites`
  },
  "/funds": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/funds`
  },
  "/lots": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/lots`
  },
  "/lots/new-listing": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]), gameId?: (string), gameSection?: (string) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/lots/new-listing${appendSp({ gameId: params?.gameId, gameSection: params?.gameSection })}`
  },
  "/lots/new-order/[lotId]": (params: { lotId: (string | number), locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/lots/new-order/${params.lotId}`
  },
  "/messages": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/messages`
  },
  "/purchases": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/purchases`
  },
  "/purchases/[orderId]": (params: { orderId: (string | number), locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/purchases/${params.orderId}`
  },
  "/referral": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/referral`
  },
  "/sales": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/sales`
  },
  "/about": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/about`
  },
  "/ai-assistant": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/ai-assistant`
  },
  "/blog": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/blog`
  },
  "/feedback": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/feedback`
  },
  "/g/[gameId]": (params: { gameId: (string | number), locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]), gameSection?: (Parameters<typeof import('../../params/gameSection.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/g/${params.gameId}${params?.gameSection ? `/${params?.gameSection}`: ''}`
  },
  "/help": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/help`
  },
  "/job": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/job`
  },
  "/promotions": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/promotions`
  },
  "/top-10": (params?: { locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/top-10`
  },
  "/u/[userId]": (params: { userId: (string | number), locale?: (Parameters<typeof import('../../params/locale.ts').match>[0]) }) => {
    return `${params?.locale ? `/${params?.locale}`: ''}/u/${params.userId}`
  }
}

/**
 * SERVERS
 */
const SERVERS = {
  
}

/**
 * ACTIONS
 */
const ACTIONS = {
  
}

/**
 * LINKS
 */
const LINKS = {
  "copyright": `https://creativecommons.org/licenses/by-nc/3.0`,
  "discord": `https://discord.gg/dTzhKUSb3y`,
  "facebook": `https://facebook.com/GameValues`,
  "instagram": `https://www.instagram.com/gamevalues`,
  "telegramChat": `https://t.me/gamevalues_chat`,
  "telegramNews": `https://t.me/gamevalues_news`,
  "twitch": `https://www.twitch.tv/gamevalues`,
  "youtube": `https://www.youtube.com/channel/UCLVw1bjWVYUjRW8oBFpwx8Q`
}

type ParamValue = string | number | undefined

/**
 * Append search params to a string
 */
export const appendSp = (sp?: Record<string, ParamValue | ParamValue[]>, prefix: '?' | '&' = '?') => {
  if (sp === undefined) return ''

  const params = new URLSearchParams()
  const append = (n: string, v: ParamValue) => {
    if (v !== undefined) {
      params.append(n, String(v))
    }
  }

  for (const [name, val] of Object.entries(sp)) {
    if (Array.isArray(val)) {
      for (const v of val) {
        append(name, v)
      }
    } else {
      append(name, val)
    }
  }

  const formatted = params.toString()
  if (formatted) {
    return `${prefix}${formatted}`
  }
  return ''
}

/**
 * get the current search params
 * 
 * Could be use like this:
 * ```
 * route("/cities", { page: 2 }, { ...currentSP() })
 * ```
 */ 
export const currentSp = () => {
  const params = new URLSearchParams(window.location.search)
  const record: Record<string, string> = {}
  for (const [key, value] of params.entries()) {
    record[key] = value
  }
  return record
}

function StringOrUndefined(val: any) {
  if (val === undefined) {
    return undefined
  }

  return String(val)
}

// route function helpers
type NonFunctionKeys<T> = { [K in keyof T]: T[K] extends Function ? never : K }[keyof T]
type FunctionKeys<T> = { [K in keyof T]: T[K] extends Function ? K : never }[keyof T]
type FunctionParams<T> = T extends (...args: infer P) => any ? P : never

const AllObjs = { ...PAGES, ...ACTIONS, ...SERVERS, ...LINKS }
type AllTypes = typeof AllObjs

/**
 * To be used like this: 
 * ```ts
 * import { route } from './ROUTES'
 * 
 * route('site_id', { id: 1 })
 * ```
 */
export function route<T extends FunctionKeys<AllTypes>>(key: T, ...params: FunctionParams<AllTypes[T]>): string
export function route<T extends NonFunctionKeys<AllTypes>>(key: T): string
export function route<T extends keyof AllTypes>(key: T, ...params: any[]): string {
  if (AllObjs[key] as any instanceof Function) {
    const element = (AllObjs as any)[key] as (...args: any[]) => string
    return element(...params)
  } else {
    return AllObjs[key] as string
  }
}

/**
* Add this type as a generic of the vite plugin `kitRoutes<KIT_ROUTES>`.
*
* Full example:
* ```ts
* import type { KIT_ROUTES } from './ROUTES'
* import { kitRoutes } from 'vite-plugin-kit-routes'
*
* kitRoutes<KIT_ROUTES>({
*  PAGES: {
*    // here, key of object will be typed!
*  }
* })
* ```
*/
export type KIT_ROUTES = {
  PAGES: { '/': 'locale', '/favorites': 'locale', '/funds': 'locale', '/lots': 'locale', '/lots/new-listing': 'locale', '/lots/new-order/[lotId]': 'lotId' | 'locale', '/messages': 'locale', '/purchases': 'locale', '/purchases/[orderId]': 'orderId' | 'locale', '/referral': 'locale', '/sales': 'locale', '/about': 'locale', '/ai-assistant': 'locale', '/blog': 'locale', '/feedback': 'locale', '/g/[gameId]': 'gameId' | 'locale' | 'gameSection', '/help': 'locale', '/job': 'locale', '/promotions': 'locale', '/top-10': 'locale', '/u/[userId]': 'userId' | 'locale' }
  SERVERS: Record<string, never>
  ACTIONS: Record<string, never>
  LINKS: { 'copyright': never, 'discord': never, 'facebook': never, 'instagram': never, 'telegramChat': never, 'telegramNews': never, 'twitch': never, 'youtube': never }
  Params: { locale: never, gameId: never, gameSection: never, lotId: never, orderId: never, userId: never }
}
