// @unocss-include

export enum Gameicon {
    "i-game:apex-legends",
    "i-game:battlefield",
    "i-game:brawl-stars",
    "i-game:call-of-duty",
    "i-game:counter-strike-2-cs-go",
    "i-game:dead-by-daylight",
    "i-game:diablo",
    "i-game:dota-2",
    "i-game:elder-scrolls-online",
    "i-game:fifa",
    "i-game:fortnite",
    "i-game:genshin-impact",
    "i-game:gta-5-online",
    "i-game:hearthstone",
    "i-game:league-of-legends",
    "i-game:lineage-2",
    "i-game:minecraft",
    "i-game:mobile-games",
    "i-game:overwatch-2",
    "i-game:path-of-exile",
    "i-game:pubg-player-unknowns-battlegrounds",
    "i-game:roblox",
    "i-game:rocket-league",
    "i-game:rust",
    "i-game:standoff-2",
    "i-game:steam",
    "i-game:tom-clancys",
    "i-game:ubisoft-connect-uplay",
    "i-game:valorant",
    "i-game:warframe",
    "i-game:world-of-tanks",
    "i-game:world-of-warcraft",
}
