export { default as FooterCopyright } from "~/widgets/footer/ui/footer-copyright.svelte"
export { default as FooterLogo } from "~/widgets/footer/ui/footer-logo.svelte"
export { default as FooterPaymentMethods } from "~/widgets/footer/ui/footer-payment-methods.svelte"
export { default as FooterPolicyLinks } from "~/widgets/footer/ui/footer-policy-links.svelte"
export { default as FooterSocialLinks } from "~/widgets/footer/ui/footer-social-links.svelte"
export { default as Footer } from "~/widgets/footer/ui/footer.svelte"
