export { default as NavbarLogo } from "~/widgets/navbar/ui/navbar-logo.svelte"
export { default as NavbarStats } from "~/widgets/navbar/ui/navbar-stats.svelte"
export { default as NavbarTab } from "~/widgets/navbar/ui/navbar-tab.svelte"
export { default as NavbarTabs } from "~/widgets/navbar/ui/navbar-tabs.svelte"
export { default as Navbar } from "~/widgets/navbar/ui/navbar.svelte"
