// @unocss-include
export const HEROICONS: string[] = [
    "i-heroicons:arrows-right-left",
    "i-heroicons:arrow-small-up",
    "i-heroicons:bars-3",
    "i-heroicons:check",
    "i-heroicons:credit-card",
    "i-heroicons:envelope",
    "i-heroicons:exclamation-triangle",
    "i-heroicons:hand-thumb-down",
    "i-heroicons:hand-thumb-up",
    "i-heroicons:heart",
    "i-heroicons:heart-solid",
    "i-heroicons:inbox-stack",
    "i-heroicons:magnifying-glass",
    "i-heroicons:shopping-cart",
    "i-heroicons:x-mark",
    "i-heroicons:user",
    "i-heroicons:users",
]
