export { default as PolicyAddress } from "~/entities/policy/ui/policy-address.svelte"
export { default as PolicyCard } from "~/entities/policy/ui/policy-card.svelte"
export { default as PolicyDetails } from "~/entities/policy/ui/policy-details.svelte"
export { default as PolicyLink } from "~/entities/policy/ui/policy-link.svelte"
export { default as PolicyLinks } from "~/entities/policy/ui/policy-links.svelte"
export { default as PolicyTab } from "~/entities/policy/ui/policy-tab.svelte"
export { default as PolicyTabs } from "~/entities/policy/ui/policy-tabs.svelte"
