version: "3.8"

services:
    proxy:
        image: traefik:v2.10
        networks:
            - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - proxy:/app
        command:
            - --providers.docker.swarmmode
        deploy:
            placement:
                constraints:
                    - node.role == manager

    frontend:
        working_dir: /frontend
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env.production
        networks:
            - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
        environment:
            - NUXT_HOST=0.0.0.0
            - NUXT_PORT=80
            - NITRO_HOST=0.0.0.0
            - NITRO_PORT=80

networks:
    traefik-public:

volumes:
    proxy:
